# Notebook 1: EXPLORING AND CLEANING OLIST E-COMMERCE DATA
-------------------------------------------------------------------------------------------------

### Author: Emmanuel Aregbesola
### Date: March, 2026

In [1]:
# Import pandas library

import pandas as pd

In [2]:
# Load the data

files = {
    'customers' : 'olist_customers_dataset.csv',
    'geolocation' : 'olist_geolocation_dataset.csv',
    'order_items' : 'olist_order_items_dataset.csv',
    'payment' : 'olist_order_payments_dataset.csv',
    'reviews' : 'olist_order_reviews_dataset.csv',
    'orders' : 'olist_orders_dataset.csv',
    'products' : 'olist_products_dataset.csv',
    'sellers' : 'olist_sellers_dataset.csv',
    'product_category' : 'product_category_name_translation.csv'
}

data = {}

for name, file in files.items():
    data[name] = pd.read_csv(file)

    
    
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

### SECTION 2 -- DATA EXPLORATION

This is the section where we get an idea of what our data is all about.

In [3]:
# checking the shape of all dataframes

for name, df in data.items():
    print(f'{name} has {df.shape[0]} rows and {df.shape[1]} columns')

customers has 99441 rows and 5 columns
geolocation has 1000163 rows and 5 columns
order_items has 112650 rows and 7 columns
payment has 103886 rows and 5 columns
reviews has 99224 rows and 7 columns
orders has 99441 rows and 8 columns
products has 32951 rows and 9 columns
sellers has 3095 rows and 4 columns
product_category has 71 rows and 2 columns

In [4]:
# checking duplicated values of all dataframe

for name, df in data.items():
    print(f'{name} has {df.duplicated().sum()} duplicates')

customers has 0 duplicates
geolocation has 261831 duplicates
order_items has 0 duplicates
payment has 0 duplicates
reviews has 0 duplicates
orders has 0 duplicates
products has 0 duplicates
sellers has 0 duplicates
product_category has 0 duplicates

In [5]:
# checking null values of all dataframe

for name, df in data.items():
    print(f'{name} has {df.isna().sum().sum()} null values ')

customers has 0 null values
geolocation has 0 null values
order_items has 0 null values
payment has 0 null values
reviews has 145903 null values
orders has 4908 null values
products has 2448 null values
sellers has 0 null values
product_category has 0 null values

In [6]:
# column list of all dataframes

for name, df in data.items():
    print(f'{name}')
    print(f'{df.columns.to_list()} \n')

customers
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

geolocation
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

order_items
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

payment
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

reviews
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

orders
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

products
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

sellers
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

product_category
['product_category_name', 'product_category_name_english']

In [7]:
# Basic overview of all dataframe

for name, df in data.items():
    print(f'{name}')
    print(f'{df.head(3)} \n')

customers
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP

geolocation
   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP

order_items
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d

   shipping_limit_date  price  freight_value
0  2017-09-19 09:45:35   58.9          13.29
1  2017-05-03 11:05:13  239.9          19.93
2  2018-01-18 14:48:30  199.0          17.87

payment
                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71

reviews
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b

   review_score review_comment_title review_comment_message  \
0             4                  NaN                    NaN
1             5                  NaN                    NaN
2             5                  NaN                    NaN

  review_creation_date review_answer_timestamp
0  2018-01-18 00:00:00     2018-01-18 21:46:59
1  2018-03-10 00:00:00     2018-03-11 03:05:13
2  2018-02-17 00:00:00     2018-02-18 14:36:24

orders
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00

products
                         product_id product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5            perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                 artes
2  96bd76ec8810374ed1b65e291975717f         esporte_lazer

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0

sellers
                          seller_id  seller_zip_code_prefix     seller_city  \
0  3442f8959a84dea7ee197c632cb2df15                   13023        campinas
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844      mogi guacu
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031  rio de janeiro

  seller_state
0           SP
1           SP
2           RJ

product_category
    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto

### SECTION 3 -- DATA CLEANING

#### In this section, we will go through all the datasets that have been imported. We will clean them, then export them as a cleaned file that will be used in further notebooks

========================================================================================================================

## Customer dataset

From the exploration section, we can see that the customer dataframe does not have any duplicated rows or null values. Also, the column names are correctly formatted.

#### What to do?
* Check the data type of columns in the customer dataframe
* understand each column
* validate the data

#### Conclusion
* All the data types in each columns are correct
----------------------------------------------------------------------------------------------------------------
### customer_id: key to the orders dataset. Each order has a unique customer_id
### customer_unique_id: unique identifier of a customer.
### customer_zip_code_prefix: first five digits of customer zip code
### customer_city: customer city name
### customer_state: customer state

In [8]:
# Assign from the dict, the customer dataframe to customer_df
customer_df = data['customers']
customer_df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [9]:
# check the data types of all the columns in the customers dataframe

customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [10]:
# Validate the customer dataframe

print(f'customer dataframe has {customer_df.shape[0]} rows and {customer_df.shape[1]} columns')
print(f'customer dataframe has {customer_df.isna().sum().sum()} null values')
print(f'customer dataframe has {customer_df.duplicated().sum()} duplicated rows')

customer dataframe has 99441 rows and 5 columns
customer dataframe has 0 null values
customer dataframe has 0 duplicated rows

### Geolocation dataset

##### From the exploration section, we can see that the geolocation dataframe does not have any null values. Also, the column names are correctly formatted.

#### What to do?
* There are 26.18% duplicated rows. We have to figure out what to do with the duplicated rows. 

#### Conclusion
* The duplicated rows were dropped. The reason being that all redundant rows where all columns are exact are dropped, thereby creating a clean lookup table for other tables/dataframe.
--------------------------------------------------------------------------------------------------

### geolocation_zip_code_prefix: first 5 digits of zip code
### geolocation_lat: latitude
### geolocation_lng: longitude
### geolocation_city: city name
### geolocation_state: state

In [11]:
# Assign from the dict (data), the geolation key to geo_df

geo_df = data['geolocation']
geo_df

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [12]:
# check the data type for each column

geo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [13]:
# Check the duplicated rows

mask = geo_df.duplicated()
geo_df.loc[mask]

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
15,1046,-23.546081,-46.644820,sao paulo,SP
44,1046,-23.546081,-46.644820,sao paulo,SP
65,1046,-23.546081,-46.644820,sao paulo,SP
66,1009,-23.546935,-46.636588,sao paulo,SP
67,1046,-23.546081,-46.644820,sao paulo,SP
...,...,...,...,...,...
1000153,99970,-28.343273,-51.873734,ciriaco,RS
1000154,99950,-28.070493,-52.011342,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [14]:
# Checking how many percent of duplicated rows we have

mask_sum = mask.sum()
print(f'We have {((mask_sum/len(geo_df))*100):.2f}% duplicated rows')

We have 26.18% duplicated rows

In [15]:
# drop the duplicated rows

geo_df.drop_duplicates(inplace=True)

In [16]:
# validate data

print(f'geolocation dataframe has {geo_df.shape[0]} rows and {geo_df.shape[1]} columns')
print(f'geolocation dataframe has {geo_df.isna().sum().sum()} null values')
print(f'geolocation dataframe has {geo_df.duplicated().sum()} duplicated rows')

geolocation dataframe has 738332 rows and 5 columns
geolocation dataframe has 0 null values
geolocation dataframe has 0 duplicated rows

## order_item Datasets

##### From the exploration section, we can see that the order_items dataframe does not have any null values and duplicated rowa. Also, the column names are correctly formatted.

-------------------------------------------------------------------------------------------------------
#### What to do?
* The shipping_limit_date datatype is incorrect, we have to convert to datetime

#### Conclusion
* The shipping_limit_date column has been converted to datetime

---------------------------------------------------------------------------------------------------------
### order_id: order unique identifier
### order_item_id: sequential number identifying number of items included in the same order.
### product_id: product unique identifier
### seller_id: seller unique identifier
### shipping_limit_date: Shows the seller shipping limit date for handling the order over to the logistic partner.
### bprice: item price
### freight_value: item freight value item (if an order has more than one item the freight value is splitted between items)

In [17]:
# assign the order_item key in the dict to a order_items_df variable

order_items_df = data['order_items']
order_items_df

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [18]:
# Check the data types of all the columns in order_items_df

order_items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [19]:
# Convert the date column to date type

order_items_df['shipping_limit_date'] = pd.to_datetime(order_items_df['shipping_limit_date'], errors='coerce')

In [20]:
# validate the date column's datatype

order_items_df['shipping_limit_date'].dtype

dtype('<M8[ns]')

In [21]:
# validate order_items_df dataframe

print(f'order_items dataframe has {order_items_df.shape[0]} rows and {order_items_df.shape[1]} columns')
print(f'order_items dataframe has {order_items_df.isna().sum().sum()} null values')
print(f'order_items dataframe has {order_items_df.duplicated().sum()} duplicated rows')

order_items dataframe has 112650 rows and 7 columns
order_items dataframe has 0 null values
order_items dataframe has 0 duplicated rows

## payment dataframe

##### From the exploration section, we can see that the payment dataframe does not have any duplicated rows or null values. Also, the column names are correctly formatted.

-------------------------------------------------------------------------------------------------------------
#### What to do?
* Check the data type of columns in the payment dataframe
* understand each column
* validate the data

#### Conclusion
All datatypes in each columns are correctly formatted and the dataframe validated

----------------------------------------------------------------------------------------------------------------
### order_id: unique identifier of an order.
### payment_sequential: a customer may pay an order with more than one payment method. If he does so, a sequence will be created to
### payment_type: method of payment chosen by the customer.
### payment_installments: number of installments chosen by the customer.
### payment_value: transaction value.

In [22]:
# assign the order_item key in the dict to a payment_df variable

payment_df = data['payment']
payment_df

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [23]:
# Check the data type of each column in payment_df

payment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [24]:
# validate payment_df dataframe

print(f'payment dataframe has {payment_df.shape[0]} rows and {payment_df.shape[1]} columns')
print(f'payment dataframe has {payment_df.isna().sum().sum()} null values')
print(f'payment dataframe has {payment_df.duplicated().sum()} duplicated rows')

payment dataframe has 103886 rows and 5 columns
payment dataframe has 0 null values
payment dataframe has 0 duplicated rows

## Reviews dataframe

##### From the exploration section, we can see that the reviews dataframe does not have any duplicated rows. Also, the column names are correctly formatted.
-----------------------------------------------------------------------------------------------------------
#### What to do?
* There are over 50% missing values in both columns in the dataframe. decide whether to drop, leave, or fill them
* Change the dates' columns to datetime

#### Conclusion
* Both columns are dropped


Justification:
1. The columns are written in portugese, which is a languge barrier
2. Over 50% of data is missing from the columns, filling it would skew the analysis to be done
3. Research shows over 80% correlation with review_score with title and message

------------------------------------------------------------------------------------------------------------
### review_id: unique review identifier
### order_id: unique order identifier
### review_score: Note ranging from 1 to 5 given by the customer on a satisfaction survey.
### review_comment_title: Comment title from the review left by the customer, in Portuguese.
### review_comment_message: Comment message from the review left by the customer, in Portuguese.
### review_creation_date: Shows the date in which the satisfaction survey was sent to the customer.
### review_answer_timestamp: Shows satisfaction survey answer timestamp.

In [25]:
# assign the reviews key in the dict to a reviews_df variable

reviews_df = data['reviews']
reviews_df

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [26]:
# Check the data type of each column in reviews_df

reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [27]:
# change to datetime format

reviews_df['review_creation_date'] = pd.to_datetime(reviews_df['review_creation_date'], errors='coerce')
reviews_df['review_answer_timestamp'] = pd.to_datetime(reviews_df['review_answer_timestamp'], errors='coerce')

In [28]:
# validate the datetime columns

reviews_df['review_creation_date'].dtype
reviews_df['review_answer_timestamp'].dtype

dtype('<M8[ns]')

In [29]:
# Check the null values in each column

reviews_df.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [30]:
# check the percentage of the missing value in each column

title_na = reviews_df['review_comment_title'].isna().sum()
msg_na = reviews_df['review_comment_message'].isna().sum()

print(f'We have {((title_na/len(reviews_df))*100):.2f}% of null values in the review_comment_title column')
print(f'We have {((msg_na/len(reviews_df))*100):.2f}% of null values in the review_comment_message column')

We have 88.34% of null values in the review_comment_title column
We have 58.70% of null values in the review_comment_message column

In [31]:
# drop both review_comment_title and review_comment_message columns
reviews_df.drop(columns=['review_comment_message', 'review_comment_title'], inplace=True)

In [32]:
# validate the drop
reviews_df.isna().sum()

review_id                  0
order_id                   0
review_score               0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [33]:
# validate reviews_df dataframe

print(f'reviews dataframe has {reviews_df.shape[0]} rows and {reviews_df.shape[1]} columns')
print(f'reviews dataframe has {reviews_df.isna().sum().sum()} null values')
print(f'reviews dataframe has {reviews_df.duplicated().sum()} duplicated rows')

reviews dataframe has 99224 rows and 5 columns
reviews dataframe has 0 null values
reviews dataframe has 0 duplicated rows

## orders dataframe

##### From the exploration section, we can see that the orders dataframe does not have any duplicated rows. Also, the column names are correctly formatted.
-----------------------------------------------------------------------------------------------------------
#### What to do?
* There are missing values in the date columns in the dataframe. decide whether to drop, leave, or fill them
* Change the dates' columns to datetime

#### Conclusion
* The date columns which had null values were not dropped
Justification:
1. The order_status that corresponds to all the null values were order that were not delivered (cancelled, processing, unavailable, etc.)
2. Dropping the column might make us lose analysis that can be done on orders that were not delivered.
3. Also, in the schema. This datasets was called the core dataset

-----------------------------------------------------------------------------------------------------------
### order_id: unique identifier of the order.
### customer_id: key to the customer dataset. Each order has a unique customer_id.
### order_status: Reference to the order status (delivered, shipped, etc).
### order_purchase_timestamp: Shows the purchase timestamp.
### order_approved_at: Shows the payment approval timestamp.
### order_delivered_carrier_date: Shows the order posting timestamp. When it was handled to the logistic partner.
### order_delivered_customer_date: Shows the actual order delivery date to the customer.
### order_estimated_delivery_date: Shows the estimated delivery date that was informed to customer at the purchase moment.

In [34]:
# assign the orders key in the dict to a orders_df variable

orders_df = data['orders']
orders_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [35]:
# Check the data type of each column in orders_df

orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [36]:
# change to datetime format

orders_df['order_purchase_timestamp'] = pd.to_datetime(orders_df['order_purchase_timestamp'], errors='coerce')
orders_df['order_approved_at'] = pd.to_datetime(orders_df['order_approved_at'], errors='coerce')
orders_df['order_delivered_carrier_date'] = pd.to_datetime(orders_df['order_delivered_carrier_date'], errors='coerce')
orders_df['order_delivered_customer_date'] = pd.to_datetime(orders_df['order_delivered_customer_date'], errors='coerce')
orders_df['order_estimated_delivery_date'] = pd.to_datetime(orders_df['order_estimated_delivery_date'], errors='coerce')

In [37]:
# validate the datetime change

orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [38]:
# Check the null values

orders_df.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [39]:
# creating the dataframe for the null values in the orders_df

orders_mask = (orders_df['order_delivered_carrier_date'].isna() |
              orders_df['order_approved_at'].isna() |
              orders_df['order_delivered_customer_date'].isna())


orders_df.loc[orders_mask].head(500)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaT,NaT,2017-05-09
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaT,2018-06-28
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaT,NaT,2018-08-21
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaT,NaT,2017-10-03
154,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,NaT,2018-02-07
...,...,...,...,...,...,...,...,...
17327,151e44f3dd461fe0838b6f59f884749f,4874fe3c17665962a71cdcdf3f9cd9a0,unavailable,2018-02-22 16:06:11,2018-02-24 02:55:40,NaT,NaT,2018-03-19
17371,51df4b64807ba1804510ee0c17f1e074,1fd7161c846f050aaa41b781aed3e26e,shipped,2017-06-25 20:33:38,2017-06-26 21:43:16,2017-06-27 14:18:01,NaT,2017-07-18
17396,6ea1f20d81136864e6e10ac9cce17901,f85b68dca11d7373293f89da2b53cf73,shipped,2017-12-04 21:13:09,2017-12-06 07:13:52,2017-12-08 21:51:40,NaT,2018-01-10
17442,1b70a3be341959c3c0ea4bd4def0b526,478e7fe4d6b284021cbb2652305ad5ba,invoiced,2017-12-27 15:02:03,2017-12-27 15:10:24,NaT,NaT,2018-01-22
17475,393e604943de623d0c4d474259214378,10bb4c6dde360660c6c9c841cb172580,shipped,2018-02-23 13:07:38,2018-02-23 13:29:37,2018-02-28 22:14:16,NaT,2018-04-03

In [40]:
# Checking if there is a 'delivered' status in the null dataframe for orders_df

delivered_mask = (
    (orders_df['order_status'] == 'delivered') &
    (orders_df['order_delivered_carrier_date'].isna()) &
    (orders_df['order_approved_at'].isna()) &
    (orders_df['order_delivered_customer_date'].isna())
)

orders_df.loc[delivered_mask]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [41]:
# calculating the sum of na vlaues in the orders_df for validation

carrier_sum = orders_df['order_delivered_carrier_date'].isna().sum()
ordered_sum = orders_df['order_approved_at'].isna().sum()
customer_sum = orders_df['order_delivered_customer_date'].isna().sum()

orders_na_sum = carrier_sum + ordered_sum + customer_sum
orders_na_sum

4908

In [42]:
# validate orders_df dataframe

print(f'orders dataframe has {orders_df.shape[0]} rows and {orders_df.shape[1]} columns')
print(f'orders dataframe has {orders_df.isna().sum().sum()} null values')
print(f'orders dataframe has {orders_df.duplicated().sum()} duplicated rows')

orders dataframe has 99441 rows and 8 columns
orders dataframe has 4908 null values
orders dataframe has 0 duplicated rows

## products dataframe

##### From the exploration section, we can see that the products dataframe does not have any duplicated rows. Also, the column names are correctly formatted.
-----------------------------------------------------------------------------------------------------------
#### What to do?
* There are missing values in the dataframe. decide whether to drop, leave, or fill them
* Correct the wrongfully spelt names in the columns

#### Conclusion
* The columns which had null values were not dropped

Justification:
1. For the analysis we are planning to do, we do not need them
2. The null values only contains 0.2% of the entire rows in the products dataframe

-----------------------------------------------------------------------------------------------------------

### product_id: unique product identifier
### product_category_name: root category of product, in Portuguese.
### product_name_lenght: number of characters extracted from the product name.
### product_description_lenght: number of characters extracted from the product description.
### product_photos_qty: number of product published photos
### product_weight_g: product weight measured in grams.
### product_length_cm: product length measured in centimeters.
### product_height_cm: product height measured in centimeters.
### product_width_cm: product width measured in centimeters.

In [43]:
# assign the products key in the dict to a products_df variable

products_df = data['products']
products_df.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [44]:
# Check the data type of each column in products_df

products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [45]:
# check the columns of the null values

products_df.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [46]:


product_mask = (products_df['product_category_name'].isna() |
               products_df['product_name_lenght'].isna() |
               products_df['product_description_lenght'].isna() |
               products_df['product_photos_qty'].isna())
products_df.loc[product_mask].head(500)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
27150,c2e65424d0c3ca6c8c87576a7307eb90,NaN,NaN,NaN,NaN,1150.0,40.0,18.0,21.0
27151,da066b813a9bc3f4294eac9aa647c834,NaN,NaN,NaN,NaN,21300.0,47.0,39.0,39.0
27203,d84a83ff61bb8049f7e620bc023f373d,NaN,NaN,NaN,NaN,1450.0,30.0,5.0,30.0
27205,59456cc9f0eb749249f39d1f8f633ad3,NaN,NaN,NaN,NaN,2465.0,34.0,20.0,20.0
27235,19ac4a7de40be5bd72347162024983f2,NaN,NaN,NaN,NaN,200.0,16.0,2.0,20.0

In [47]:
# drop the nan rows

products_df.dropna(subset=['product_category_name', 
                            'product_name_lenght', 
                            'product_description_lenght', 
                            'product_photos_qty',
                            'product_weight_g',
                           'product_length_cm',
                           'product_width_cm',
                           'product_height_cm'], inplace=True)

In [48]:
# validate the drop
products_df.isna().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [49]:
products_df.rename(columns = {
    'product_name_lenght' : 'product_name_length',
    'product_description_lenght' : 'product_description_length'
}, inplace=True)

In [50]:
# validate the column change

products_df.columns.to_list()

['product_id',
 'product_category_name',
 'product_name_length',
 'product_description_length',
 'product_photos_qty',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm']

In [51]:
# validate products_df dataframe

print(f'products dataframe has {products_df.shape[0]} rows and {products_df.shape[1]} columns')
print(f'products dataframe has {products_df.isna().sum().sum()} null values')
print(f'products dataframe has {products_df.duplicated().sum()} duplicated rows')

products dataframe has 32340 rows and 9 columns
products dataframe has 0 null values
products dataframe has 0 duplicated rows

## sellers dataframe

##### From the exploration section, we can see that the sellers dataframe does not have any duplicated rows or null values. Also, the column names are correctly formatted.
-----------------------------------------------------------------------------------------------------------

#### Conclusion
The data in this dataframe is correctly formated.

-----------------------------------------------------------------------------------------------------------
### seller_id: seller unique identifier
### seller_zip_code_prefix: first 5 digits of seller zip code
### seller_city: seller city name
### seller_state: seller state

In [52]:
# assign the sellers key in the dict to a sellers_df variable

sellers_df = data['sellers']
sellers_df.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [53]:
# Check the data type of each column in sellers_df

sellers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [54]:
# validate sellers_df dataframe

print(f'sellers dataframe has {sellers_df.shape[0]} rows and {sellers_df.shape[1]} columns')
print(f'sellers dataframe has {sellers_df.isna().sum().sum()} null values')
print(f'sellers dataframe has {sellers_df.duplicated().sum()} duplicated rows')

sellers dataframe has 3095 rows and 4 columns
sellers dataframe has 0 null values
sellers dataframe has 0 duplicated rows

## product_category

##### From the exploration section, we can see that the product_category dataframe does not have any duplicated rows or null values. Also, the column names are correctly formatted.
-----------------------------------------------------------------------------------------------------------

#### Conclusion
The data in this dataframe is correctly formated.

-----------------------------------------------------------------------------------------------------------
### product_category_name: category name in Portuguese
### product_category_name_english: category name in English

In [55]:
# assign the product_category key in the dict to a product_category_df variable

product_category_df = data['product_category']
product_category_df.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [56]:
# Check the data type of each column in product_category_df

product_category_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [57]:
# validate product_category_df dataframe

print(f'product_category dataframe has {product_category_df.shape[0]} rows and {product_category_df.shape[1]} columns')
print(f'product_category dataframe has {product_category_df.isna().sum().sum()} null values')
print(f'product_category dataframe has {product_category_df.duplicated().sum()} duplicated rows')

product_category dataframe has 71 rows and 2 columns
product_category dataframe has 0 null values
product_category dataframe has 0 duplicated rows

In [58]:
# Save all cleaned data into a csv file

cleaned_data = {
    'customers': customer_df,
    'geolocation': geo_df,
    'order_items': order_items_df,
    'payment': payment_df,
    'reviews': reviews_df,
    'orders': orders_df,
    'products': products_df,
    'sellers': sellers_df,
    'product_category': product_category_df
}


for name, df in cleaned_data.items():
    df.to_csv(f'cleaned_{name}.csv', index=False)
    print(f"✓ Saved: cleaned_{name}.csv ({len(df)} rows)")
    
print(f'All cleaned dataframe are saved!')

✓ Saved: cleaned_customers.csv (99441 rows)
✓ Saved: cleaned_geolocation.csv (738332 rows)
✓ Saved: cleaned_order_items.csv (112650 rows)
✓ Saved: cleaned_payment.csv (103886 rows)
✓ Saved: cleaned_reviews.csv (99224 rows)
✓ Saved: cleaned_orders.csv (99441 rows)
✓ Saved: cleaned_products.csv (32340 rows)
✓ Saved: cleaned_sellers.csv (3095 rows)
✓ Saved: cleaned_product_category.csv (71 rows)
All cleaned dataframe are saved!

## Summary
--------------------------------------------------------------------------------
✅ All 9 datasets cleaned and saved

**Files saved:**
- cleaned_customers.csv
- cleaned_geolocation.csv  
- cleaned_order_items.csv
- cleaned_payments.csv
- cleaned_reviews.csv
- cleaned_orders.csv
- cleaned_products.csv
- cleaned_sellers.csv
- cleaned_product_category.csv

**Next:** Move to Analysis_and_Visualization notebook